# Generated by Django 3.1.1 on 2020-10-02 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_imagegallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageGallery',
            new_name='imggal',
        ),
    ]
